[project]
name = "payment-service-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "woozlic", email = "sampaccs@mail.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
    "environs[django]>=15.2.0",
    "gunicorn>=26.2.0",
    "psycopg[binary]>=3.3.5",
]

[project.scripts]
payment-service-django = "payment_service_django:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "django-stubs>=6.1.0",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-django>=4.14.0",
    "ruff>=0.16.6",
]
