# Generated by Django 6.1.1 on 2026-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
