# Generated by Django 6.1.1 on 2026-09-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payout_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='payout_uuid',
        ),
        migrations.AddField(
            model_name='payout',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
