# Generated by Django 6.1.1 on 2026-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_remove_payout_payout_uuid_payout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
